name: Deploy Web

on:
  push:
    tags:
      - 'v[0-9]+.[0-9]+.[0-9]+'

jobs:
  build_and_deploy_web:
    name: Build and deploy web
    type: deploy
    environment: production
    params:
      prod: true
